# Makefile.in generated automatically by automake 1.5 from Makefile.am.

# Copyright 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001
# Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



SHELL = /bin/sh

srcdir = .
top_srcdir = ../..

prefix = /home/kkho/em_beta
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/info
mandir = ${prefix}/man
includedir = ${prefix}/include
oldincludedir = /usr/include
pkgdatadir = $(datadir)/emerald
pkglibdir = $(libdir)/emerald
pkgincludedir = $(includedir)/emerald
top_builddir = ../..

ACLOCAL = ${SHELL} /home/kkho/emerald/missing --run aclocal
AUTOCONF = ${SHELL} /home/kkho/emerald/missing --run autoconf
AUTOMAKE = ${SHELL} /home/kkho/emerald/missing --run automake
AUTOHEADER = ${SHELL} /home/kkho/emerald/missing --run autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
INSTALL_HEADER = $(INSTALL_DATA)
transform = s,x,x,
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
AMTAR = ${SHELL} /home/kkho/emerald/missing --run tar
AWK = gawk
CC = gcc
DEPDIR = .deps
EXEEXT = 
INSTALL_STRIP_PROGRAM = ${SHELL} $(install_sh) -c -s
LEX = flex
LN_S = ln -s
OBJEXT = o
PACKAGE = emerald
RANLIB = ranlib
SH = /bin/sh
VERSION = 1.06alpha
YACC = bison -y
am__include = include
am__quote = 
install_sh = /home/kkho/emerald/install-sh

bin_PROGRAMS = emx

noinst_PROGRAMS = codeptrextra 

noinst_SCRIPTS = gencodeptrextra.sh

EXTRA_DIST = gencodeptrextra.sh

codeptrextra_SOURCES = codeptrextra.c

emx_SOURCES = array.c \
	bufstr.c \
	call.c \
	conform.c \
	creation.c \
	debug.c \
	dist.c \
	distgc.c \
	filestr.c \
	gaggle.c \
	gc.c \
	globals.c \
	iisc.c \
	iixsc.c \
	io.c \
	iosc.c \
	iset.c \
	joveisc.c \
	jsys.c \
	jvisc.c \
	locate.c \
	main.c \
	misc.c \
	move.c \
	mqueue.c \
	oidtoobj.c \
	oisc.c \
	ooisc.c \
	otable.c \
	read.c \
	remote.c \
	rinvoke.c \
	squeue.c \
	storage.c \
	streams.c \
	timer.c \
	trace.c \
	upcall.c \
	vm.c \
	write.c \
	cctab.c 

#\
#	$(X11SRC) \
#	$(LWPSRC)
include_HEADERS = \
	array.h \
	assert.h \
	bufstr.h \
	builtins.h \
	call.h \
	concurr.h \
	config.h \
	creation.h \
	dist.h \
	extract.h \
	filestr.h \
	gaggle.h \
	gc.h \
	globals.h \
	iisc.h \
	iixsc.h \
	init.h \
	insert.h \
	io.h \
	iosc.h \
	iset.h \
	joveisc.h \
	jsys.h \
	jvisc.h \
	locate.h \
	misc.h \
	move.h \
	mqueue.h \
	oidtoobj.h \
	oisc.h \
	ooisc.h \
	otable.h \
	read.h \
	remote.h \
	rinvoke.h \
	squeue.h \
	storage.h \
	streams.h \
	system.h \
	timer.h \
	trace.h \
	types.h \
	vm.h \
	vm_i.h \
	vm_exp.h \
	write.h \
	cctab.h \
	codeptrextra.h 


#\
#	$(X11INC) \
#	$(LWPINC)
emx_LDADD = ../../ccalls/libccalls.a

EMERALDROOT = $(top_srcdir)

BUILT_SOURCES = cctab.c codeptrextra.h

CLEANFILES = cctab.c cctab.h codeptrextra.h
subdir = vm/src
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES =
bin_PROGRAMS = emx$(EXEEXT)
noinst_PROGRAMS = codeptrextra$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS) $(noinst_PROGRAMS)

am_codeptrextra_OBJECTS = codeptrextra.$(OBJEXT)
codeptrextra_OBJECTS = $(am_codeptrextra_OBJECTS)
codeptrextra_LDADD = $(LDADD)
codeptrextra_DEPENDENCIES =
codeptrextra_LDFLAGS =
am_emx_OBJECTS = array.$(OBJEXT) bufstr.$(OBJEXT) call.$(OBJEXT) \
	conform.$(OBJEXT) creation.$(OBJEXT) debug.$(OBJEXT) \
	dist.$(OBJEXT) distgc.$(OBJEXT) filestr.$(OBJEXT) \
	gaggle.$(OBJEXT) gc.$(OBJEXT) globals.$(OBJEXT) iisc.$(OBJEXT) \
	iixsc.$(OBJEXT) io.$(OBJEXT) iosc.$(OBJEXT) iset.$(OBJEXT) \
	joveisc.$(OBJEXT) jsys.$(OBJEXT) jvisc.$(OBJEXT) \
	locate.$(OBJEXT) main.$(OBJEXT) misc.$(OBJEXT) move.$(OBJEXT) \
	mqueue.$(OBJEXT) oidtoobj.$(OBJEXT) oisc.$(OBJEXT) \
	ooisc.$(OBJEXT) otable.$(OBJEXT) read.$(OBJEXT) \
	remote.$(OBJEXT) rinvoke.$(OBJEXT) squeue.$(OBJEXT) \
	storage.$(OBJEXT) streams.$(OBJEXT) timer.$(OBJEXT) \
	trace.$(OBJEXT) upcall.$(OBJEXT) vm.$(OBJEXT) write.$(OBJEXT) \
	cctab.$(OBJEXT)
emx_OBJECTS = $(am_emx_OBJECTS)
emx_DEPENDENCIES = ../../ccalls/libccalls.a
emx_LDFLAGS =
SCRIPTS = $(noinst_SCRIPTS)


DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE=\"emerald\" -DVERSION=\"1.06alpha\" -DSINGLESTEP=1 -DCOUNTBYTECODES=1 -DSTDARG_WORKS=1 -DDISTRIBUTED=1 -DYYTEXT_POINTER=1 -DHAVE_LIBL=1 -DHAVE_LIBM=1 -DHAVE_DIRENT_H=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_FCNTL_H=1 -DHAVE_SYS_FILE_H=1 -DHAVE_SYS_TIME_H=1 -DHAVE_UNISTD_H=1 -DTIME_WITH_SYS_TIME=1 -DRETSIGTYPE=void -DHAVE_STRFTIME=1 -DHAVE_VPRINTF=1 -DHAVE_FTIME=1 -DHAVE_GETHOSTNAME=1 -DHAVE_GETTIMEOFDAY=1 -DHAVE_MKTIME=1 -DHAVE_REGCOMP=1 -DHAVE_SOCKET=1 -DHAVE_STRCSPN=1 -DHAVE_STRERROR=1 
DEFAULT_INCLUDES =  -I. -I$(srcdir)
CPPFLAGS = 
LDFLAGS = 
LIBS = -lm -ll 
depcomp = $(SHELL) $(top_srcdir)/depcomp
DEP_FILES = $(DEPDIR)/array.Po $(DEPDIR)/bufstr.Po \
	$(DEPDIR)/call.Po $(DEPDIR)/cctab.Po \
	$(DEPDIR)/codeptrextra.Po $(DEPDIR)/conform.Po \
	$(DEPDIR)/creation.Po $(DEPDIR)/debug.Po \
	$(DEPDIR)/dist.Po $(DEPDIR)/distgc.Po \
	$(DEPDIR)/filestr.Po $(DEPDIR)/gaggle.Po \
	$(DEPDIR)/gc.Po $(DEPDIR)/globals.Po \
	$(DEPDIR)/iisc.Po $(DEPDIR)/iixsc.Po \
	$(DEPDIR)/io.Po $(DEPDIR)/iosc.Po $(DEPDIR)/iset.Po \
	$(DEPDIR)/joveisc.Po $(DEPDIR)/jsys.Po \
	$(DEPDIR)/jvisc.Po $(DEPDIR)/locate.Po \
	$(DEPDIR)/main.Po $(DEPDIR)/misc.Po \
	$(DEPDIR)/move.Po $(DEPDIR)/mqueue.Po \
	$(DEPDIR)/oidtoobj.Po $(DEPDIR)/oisc.Po \
	$(DEPDIR)/ooisc.Po $(DEPDIR)/otable.Po \
	$(DEPDIR)/read.Po $(DEPDIR)/remote.Po \
	$(DEPDIR)/rinvoke.Po $(DEPDIR)/squeue.Po \
	$(DEPDIR)/storage.Po $(DEPDIR)/streams.Po \
	$(DEPDIR)/timer.Po $(DEPDIR)/trace.Po \
	$(DEPDIR)/upcall.Po $(DEPDIR)/vm.Po \
	$(DEPDIR)/write.Po
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
CFLAGS = -g -O2
DIST_SOURCES = $(codeptrextra_SOURCES) $(emx_SOURCES)
HEADERS = $(include_HEADERS)

DIST_COMMON = $(include_HEADERS) Makefile.am Makefile.in
SOURCES = $(codeptrextra_SOURCES) $(emx_SOURCES)

all: $(BUILT_SOURCES)
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
$(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.ac $(ACLOCAL_M4)
	cd $(top_srcdir) && \
	  $(AUTOMAKE) --gnu  vm/src/Makefile
Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) && \
	  CONFIG_HEADERS= CONFIG_LINKS= \
	  CONFIG_FILES=$(subdir)/$@ $(SHELL) ./config.status
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
	  if test -f $$p \
	  ; then \
	    f=`echo $$p1|sed '$(transform);s/$$/$(EXEEXT)/'`; \
	   echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f"; \
	   $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/$$f; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  f=`echo $$p|sed 's/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
	  rm -f $(DESTDIR)$(bindir)/$$f; \
	done

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
codeptrextra$(EXEEXT): $(codeptrextra_OBJECTS) $(codeptrextra_DEPENDENCIES) 
	@rm -f codeptrextra$(EXEEXT)
	$(LINK) $(codeptrextra_LDFLAGS) $(codeptrextra_OBJECTS) $(codeptrextra_LDADD) $(LIBS)
emx$(EXEEXT): $(emx_OBJECTS) $(emx_DEPENDENCIES) 
	@rm -f emx$(EXEEXT)
	$(LINK) $(emx_LDFLAGS) $(emx_OBJECTS) $(emx_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT) core *.core

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/array.Po
include $(DEPDIR)/bufstr.Po
include $(DEPDIR)/call.Po
include $(DEPDIR)/cctab.Po
include $(DEPDIR)/codeptrextra.Po
include $(DEPDIR)/conform.Po
include $(DEPDIR)/creation.Po
include $(DEPDIR)/debug.Po
include $(DEPDIR)/dist.Po
include $(DEPDIR)/distgc.Po
include $(DEPDIR)/filestr.Po
include $(DEPDIR)/gaggle.Po
include $(DEPDIR)/gc.Po
include $(DEPDIR)/globals.Po
include $(DEPDIR)/iisc.Po
include $(DEPDIR)/iixsc.Po
include $(DEPDIR)/io.Po
include $(DEPDIR)/iosc.Po
include $(DEPDIR)/iset.Po
include $(DEPDIR)/joveisc.Po
include $(DEPDIR)/jsys.Po
include $(DEPDIR)/jvisc.Po
include $(DEPDIR)/locate.Po
include $(DEPDIR)/main.Po
include $(DEPDIR)/misc.Po
include $(DEPDIR)/move.Po
include $(DEPDIR)/mqueue.Po
include $(DEPDIR)/oidtoobj.Po
include $(DEPDIR)/oisc.Po
include $(DEPDIR)/ooisc.Po
include $(DEPDIR)/otable.Po
include $(DEPDIR)/read.Po
include $(DEPDIR)/remote.Po
include $(DEPDIR)/rinvoke.Po
include $(DEPDIR)/squeue.Po
include $(DEPDIR)/storage.Po
include $(DEPDIR)/streams.Po
include $(DEPDIR)/timer.Po
include $(DEPDIR)/trace.Po
include $(DEPDIR)/upcall.Po
include $(DEPDIR)/vm.Po
include $(DEPDIR)/write.Po

distclean-depend:
	-rm -rf $(DEPDIR)

.c.o:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `test -f $< || echo '$(srcdir)/'`$<

.c.obj:
	source='$<' object='$@' libtool=no \
	depfile='$(DEPDIR)/$*.Po' tmpdepfile='$(DEPDIR)/$*.TPo' \
	$(CCDEPMODE) $(depcomp) \
	$(COMPILE) -c `cygpath -w $<`
CCDEPMODE = depmode=gcc3
uninstall-info-am:
install-includeHEADERS: $(include_HEADERS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(includedir)
	@list='$(include_HEADERS)'; for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " $(INSTALL_HEADER) $$d$$p $(DESTDIR)$(includedir)/$$f"; \
	  $(INSTALL_HEADER) $$d$$p $(DESTDIR)$(includedir)/$$f; \
	done

uninstall-includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(include_HEADERS)'; for p in $$list; do \
	  f="`echo $$p | sed -e 's|^.*/||'`"; \
	  echo " rm -f $(DESTDIR)$(includedir)/$$f"; \
	  rm -f $(DESTDIR)$(includedir)/$$f; \
	done

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	mkid -fID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || etags $(ETAGS_ARGS) $$tags  $$unique $(LISP)

GTAGS:
	here=`CDPATH=: && cd $(top_builddir) && pwd` \
	  && cd $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) $$here

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH

DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)

top_distdir = ../..
distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  if test -f $$file; then d=.; else d=$(srcdir); fi; \
	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
	  if test "$$dir" != "$$file" && test "$$dir" != "."; then \
	    $(mkinstalldirs) "$(distdir)/$$dir"; \
	  fi; \
	  if test -d $$d/$$file; then \
	    cp -pR $$d/$$file $(distdir) \
	    || exit 1; \
	  else \
	    test -f $(distdir)/$$file \
	    || cp -p $$d/$$file $(distdir)/$$file \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(SCRIPTS) $(HEADERS)

installdirs:
	$(mkinstalldirs) $(DESTDIR)$(bindir) $(DESTDIR)$(includedir)

install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES) stamp-h stamp-h[0-9]*

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(BUILT_SOURCES)" || rm -f $(BUILT_SOURCES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-noinstPROGRAMS \
	mostlyclean-am

distclean: distclean-am

distclean-am: clean-am distclean-compile distclean-depend \
	distclean-generic distclean-tags

dvi: dvi-am

dvi-am:

info: info-am

info-am:

install-data-am: install-includeHEADERS

install-exec-am: install-binPROGRAMS

install-info: install-info-am

install-man:

installcheck-am:

maintainer-clean: maintainer-clean-am

maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

uninstall-am: uninstall-binPROGRAMS uninstall-includeHEADERS \
	uninstall-info-am

.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
	clean-generic clean-noinstPROGRAMS distclean distclean-compile \
	distclean-depend distclean-generic distclean-tags distdir dvi \
	dvi-am info info-am install install-am install-binPROGRAMS \
	install-data install-data-am install-exec install-exec-am \
	install-includeHEADERS install-info install-info-am install-man \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic tags uninstall \
	uninstall-am uninstall-binPROGRAMS uninstall-includeHEADERS \
	uninstall-info-am


codeptrextra.h:	codeptrextra
	./gencodeptrextra.sh

cctab.h: cctab.c

cctab.c: Makefile
	EMERALDROOT=$(top_srcdir) $(top_srcdir)/bin/gencctab.sh `cd $(top_srcdir)/ccalls;ls *.o`
# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
